export const events = [
    {
        date: "24/06/2023",
        eventName: "Event 1",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Recaudación",
    },
    {
        date: "25/06/2023",
        eventName: "Event 2",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Recaudación",
    },
    {
        date: "26/06/2023",
        eventName: "Event 3",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Recaudación",
    },
    {
        date: "27/06/2024",
        eventName: "Event 4",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Campaña de esterilización",
    },
    {
        date: "29/06/2024",
        eventName: "Event 5",
        location: "San Salvador",
        description: "Lorem ipsum 2",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Campaña de esterilización",
    },
    {
        date: "30/06/2024",
        eventName: "Event 6",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Festival de mascotas",
    },
    {
        date: "01/07/2024",
        eventName: "Event 7",
        location: "La Libertad",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Festival de mascotas",
    },
    {
        date: "02/07/2024",
        eventName: "Event 8",
        location: "La Libertad",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Festival de mascotas",
    },
    {
        date: "02/07/2024",
        eventName: "Event 9",
        location: "La Libertad",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage:"https://cataas.com/cat",
        eventType: "Recaudación",
    },
];