export const events = [
    {
        date: "24/06/2023",
        eventName: "Event 1",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Recaudación",
        eventHour: "17:00",
        eventBudget: "$100.00",
        eventStatus: "pendiente",
        eventCreatedBy: "",
    },
    {
        date: "25/06/2023",
        eventName: "Event 2",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Recaudación",
        eventHour: "18:00",
        eventBudget: "$200.00",
        eventStatus: "aprobado",
        eventCreatedBy: "",
    },
    {
        date: "26/06/2023",
        eventName: "Event 3",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Recaudación",
        eventHour: "12:00",
        eventBudget: "$300.00",
        eventStatus: "pendiente",
        eventCreatedBy: "",
    },
    {
        date: "27/06/2024",
        eventName: "Event 4",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Campaña de esterilización",
        eventHour: "16:00",
        eventBudget: "$200.00",
        eventStatus: "declinado",
        eventCreatedBy: "",
    },
    {
        date: "29/06/2024",
        eventName: "Event 5",
        location: "San Salvador",
        description: "Lorem ipsum 2",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Campaña de esterilización",
        eventHour: "09:00",
        eventBudget: "$200.00",
        eventStatus: "aprobado",
        eventCreatedBy: "",
    },
    {
        date: "30/06/2024",
        eventName: "Event 6",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Festival de mascotas",
        eventHour: "20:00",
        eventBudget: "$200.00",
        eventStatus: "pendiente",
        eventCreatedBy: "",
    },
    {
        date: "01/07/2024",
        eventName: "Event 7",
        location: "La Libertad",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Festival de mascotas",
        eventHour: "08:00",
        eventBudget: "$700.00",
        eventStatus: "aprobado",
        eventCreatedBy: "",
    },
    {
        date: "02/07/2024",
        eventName: "Event 8",
        location: "La Libertad",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Festival de mascotas",
        eventHour: "13:00",
        eventBudget: "$800.00",
        eventStatus: "aprobado",
        eventCreatedBy: "",
    },
    {
        date: "02/07/2024",
        eventName: "Event 9",
        location: "La Libertad",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        eventImage: "https://cataas.com/cat",
        eventType: "Recaudación",
        eventHour: "15:00",
        eventBudget: "$200.00",
        eventStatus: "pendiente",
        eventCreatedBy: "",
    },
];

export const news = [
    {
        dateCreated: "24/06/2023",
        newsTitle: "News 1",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Recomendaciones",
        newsCreatedBy: "Buenas",
    },
    {
        dateCreated: "29/06/2023",
        newsTitle: "News 2",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Success Story",
        newsCreatedBy: "",
        
    },
    {
        dateCreated: "30/06/2023",
        newsTitle: "News 3",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Blog",
        newsCreatedBy: "",
    },
    {
        dateCreated: "30/06/2023",
        newsTitle: "News 4",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Servicio Social",
        newsCreatedBy: "",
    },
    {
        dateCreated: "31/06/2023",
        newsTitle: "News 5",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Servicio Social",
        newsCreatedBy: "",
    },
    {
        dateCreated: "01/07/2023",
        newsTitle: "News 6",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Servicio Social",
        newsCreatedBy: "",
    },
    {
        dateCreated: "05/07/2023",
        newsTitle: "News 7",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Blog",
        newsCreatedBy: "",
    },
    {
        dateCreated: "07/07/2023",
        newsTitle: "News 8",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Success Story",
        newsCreatedBy: "",
    },
    {
        dateCreated: "08/07/2023",
        newsTitle: "News 9",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Success Story",
        newsCreatedBy: "",
    },
    {
        dateCreated: "10/07/2023",
        newsTitle: "News 10",
        location: "San Salvador",
        description: "Lorem ipsum 1 Lorem ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1 ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1ipsum 1 Lorem ipsum 1 Lorem aaaaa ipsum 1 Lorem aaaaa ipsum 1",
        viewType: "",
        newsImage: "https://cataas.com/cat",
        newsType: "Servicio Social",
        newsCreatedBy: "",
    },

];


export const catsData = [
    {
        nameCat: "Poppy",
        colorCat: "Orange",
        ageCat: "Senior",
        sexCat: "Female",
        gatoImage: "https://cataas.com/cat"

    },
    {
        nameCat: "kiki",
        colorCat: "white",
        ageCat: "Kitten",
        sexCat: "Male",
        gatoImage: "https://cataas.com/cat"
    },
    {
        nameCat: "name",
        colorCat: "color",
        ageCat: "age",
        sexCat: "sex",
        gatoImage: "https://cataas.com/cat"
    },
    {
        nameCat: "name",
        colorCat: "color",
        ageCat: "age",
        sexCat: "sex",
        gatoImage: "https://cataas.com/cat"
    },
    {
        nameCat: "name",
        colorCat: "color",
        ageCat: "age",
        sexCat: "sex",
        gatoImage: "https://cataas.com/cat"
    },
    {
        nameCat: "name",
        colorCat: "color",
        ageCat: "age",
        sexCat: "sex",
        gatoImage: "https://cataas.com/cat"
    },
    {
        nameCat: "name",
        colorCat: "color",
        ageCat: "age",
        sexCat: "sex",
        gatoImage: "https://cataas.com/cat"
    },
    {
        nameCat: "name",
        colorCat: "color",
        ageCat: "age",
        sexCat: "sex",
        gatoImage: "https://cataas.com/cat"
    },
    {
        nameCat: "name",
        colorCat: "color",
        ageCat: "age",
        sexCat: "sex",
        gatoImage: "https://cataas.com/cat"
    }

]


export const user = [
    {
        id: "1",
        userName: "UsuarioAdmin",
        userLastName: "AdminUsuario",
        userEmail: "admin@gmail.com",
        password: "123456",
        roleId: "1",
        userPhone: "503 7777 7777",
        userAddress: "Rpto Metro",
        userDepto: "San Salvador",
        userDescription: "About me.......",
        userProfilePic: "https://i0.wp.com/puppis.blog/wp-content/uploads/2022/02/abc-cuidado-de-los-gatos-min.jpg?resize=1024%2C681&ssl=1",
    },
    {
        id: "2",
        userName: "UsuarioModerador",
        userLastName: "ModeradorUsuario",
        userEmail: "moderador@gmail.com",
        password: "123456",
        roleId: "2",
        userPhone: "503 7777 8888",
        userAddress: "Proceres Blv",
        userDepto: "La Libertad",
        userDescription: "About me!!!!!!",
        userProfilePic: "https://preview.redd.it/exhausted-cat-developer-v0-kaepljx1y93a1.jpg?width=640&crop=smart&auto=webp&s=fcc47d300bbbe914b596f511dfb642a35f09f22f",
    },
    {
        id: "5",
        userName: "UsuarioModerador2",
        userLastName: "ModeradorUsuario2",
        userEmail: "moderador2@gmail.com",
        password: "123456",
        roleId: "2",
        userPhone: "503 7777 8888",
        userAddress: "Proceres Blv",
        userDepto: "La Libertad",
        userDescription: "About me!!!!!!",
        userProfilePic: "https://img-9gag-fun.9cache.com/photo/ap93yAE_460s.jpg",
    },
    {
        id: "3",
        userName: "UsuarioUsuario",
        userLastName: "UsuarioUsuario",
        userEmail: "usuario@gmail.com",
        password: "123456",
        roleId: "3",
        userPhone: "503 7777 9999",
        userAddress: "Calle las pupusas",
        userDepto: "La paz",
        userDescription: "About me?????",
        userProfilePic: "https://cataas.com/cat",
    },
    {
        id: "4",
        userName: "UsuarioUsuario2",
        userLastName: "UsuarioUsuario2",
        userEmail: "usuario2@gmail.com",
        password: "123456",
        roleId: "3",
        userPhone: "503 7777 0000",
        userAddress: "Calle las riguas",
        userDepto: "Cuscatlan",
        userDescription: "About me??!!?",
        userProfilePic: "https://cataas.com/cat",
    },
    {
        id: "5",
        userName: "UsuarioUsuario3",
        userLastName: "UsuarioUsuario3",
        userEmail: "usuario3@gmail.com",
        password: "123456",
        roleId: "3",
        userPhone: "503 7777 0000",
        userAddress: "Calle el atol",
        userDepto: "Morazan",
        userDescription: "About me??!!?",
        userProfilePic: "https://cataas.com/cat",
    },
];

export const formSubmissions = [
    {
        imagenCat: "undefined",
        nomGato: "Poppy",
        nombre: "daniela",
        fechaNacimiento: "2016-09-20",
        telefono: "2222-2122",
        apellido: "roda",
        email: "maria@daniela",
        direccion: "mi choza",
        educacion: "Media",
        profesion: "chef",
        tipoInmueble: "Apartamento",
        espacioChecked: false,
        acuerdoChecked: false,
        gastos: "200",
        alergias: "si alergia",
        razon: "pq es lindo",
        mascotas: "",
        mascotasPasadas: "si he tenido gato",
        responsabilidadChecked: false,
        cuidados: "cuidados",
        renuncia: "ninguna",
        aceptoChecked: false,
        responsabilidad: false,
        otrasMascotas: "no mas mascotas",
        conocimientoCuidados: "si conozco cuidado",
        circunstanciasRenuncia: "mi muerte",
        submissionDate: "2023-11-30T00:17:20.927Z"
    },
    {
        imagenCat: "undefined",
        nomGato: "Kiki",
        nombre: "dorotea",
        fechaNacimiento: "1999-11-10",
        telefono: "33223322",
        apellido: "mendez",
        email: "dora@mendez",
        direccion: "mi casita",
        educacion: "Media",
        profesion: "Doctora",
        tipoInmueble: "Apartamento",
        espacioChecked: true,
        acuerdoChecked: true,
        gastos: "800",
        alergias: "no hay alergicos",
        razon: "pq quiero compañia",
        mascotas: "",
        mascotasPasadas: "si he tenido gato",
        responsabilidadChecked: false,
        cuidados: "",
        renuncia: "",
        aceptoChecked: false,
        responsabilidad: true,
        otrasMascotas: "si tengo otro gato",
        conocimientoCuidados: "si conozco cuidado muy bien",
        circunstanciasRenuncia: "me mudo de pais",
        submissionDate: "2023-11-30T00:32:29.359Z"
    }
];
